# Generated by Django 4.2.3 on 2023-07-23 20:39

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CurrencyConvertionEventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "api_request_amount",
                    models.DecimalField(
                        decimal_places=5, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("api_request_from_currency", models.CharField(max_length=3)),
                (
                    "api_response_converted_amount",
                    models.DecimalField(
                        decimal_places=5, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("api_request_to_currency", models.CharField(max_length=3)),
                ("api_request_exchange_rate_datetime", models.DateTimeField()),
                ("api_response_status_code", models.PositiveSmallIntegerField()),
                ("api_response_body", models.JSONField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
