# Generated by Django 4.2.3 on 2023-07-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyconvertioneventlog",
            name="api_response_exchange_rate_datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="currencyconvertioneventlog",
            name="api_response_converted_amount",
            field=models.DecimalField(
                decimal_places=5, default=None, max_digits=20, null=True
            ),
        ),
    ]
